// config parser functions
void f_pid(char *);
void f_trace(int);
void f_autoindex(int);
void f_sendfile(int);
void f_tcpnopush(int);
void f_user(char *, char *);
void f_server();
void f_http();
void f_root(char *);
void f_expires(char *);
void f_server_name(char *, int);
void f_indexFile(char *);
void f_error_log(char *);
void f_access_log(char *, int);
void f_ssl_certificate(char *);
void f_ssl_certificate_key(char *);
void f_listen(char *, int);
void f_tls();
void f_location(int, char *, char *);
void f_try_files();
void f_try_target(char *);
void f_proxy_pass(char *, int);
void f_protocol(char *);
void f_keepalive_timeout(int);
void f_workerProcesses(int);
void f_workerConnections(int);
void f_events();
